language: python
python:
  - "3.9.1"
addons:
  chrome: stable
before_script:
  - wget https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.9.1/bin/
  - export CHROME_BIN=chromium-browser
install:
  - pip install pipenv
  - pipenv install
script:
  - python hotukdeals.py
  - python mail.py